//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accuracy
    {
        public int ID { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public string Updated { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public Nullable<int> Order { get; set; }
        public string AccuracyName { get; set; }
    }
}
