//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReps
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string DivisionGroupCommonName { get; set; }
        public string DivisionGroupCommonCode { get; set; }
        public string DivisionAbbrName { get; set; }
        public string DivisionAbbrCode { get; set; }
        public string DepartmentAbbrName { get; set; }
        public string DepartmentAbbrCode { get; set; }
        public string HENCustomerNameKana { get; set; }
        public string HENCustomerName { get; set; }
        public string HENCustomerRepCode { get; set; }
        public string MidClassIndustryID { get; set; }
    }
}
