//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMPZDDB : DbContext
    {
        public HMPZDDB()
            : base("name=HMPZDDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accuracy> Accuracy { get; set; }
        public virtual DbSet<AdvertisementTypes> AdvertisementTypes { get; set; }
        public virtual DbSet<BARepresentatives> BARepresentatives { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<CooperativeCompany> CooperativeCompany { get; set; }
        public virtual DbSet<CustomerRepExclusionConditions> CustomerRepExclusionConditions { get; set; }
        public virtual DbSet<CustomerReps> CustomerReps { get; set; }
        public virtual DbSet<CustomerRepSearchLogs> CustomerRepSearchLogs { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DisplayPeriods> DisplayPeriods { get; set; }
        public virtual DbSet<ElectronLedgerChangeLog> ElectronLedgerChangeLog { get; set; }
        public virtual DbSet<IndustryMidClassifications> IndustryMidClassifications { get; set; }
        public virtual DbSet<LockedPeriods> LockedPeriods { get; set; }
        public virtual DbSet<MagazineRepresentatives> MagazineRepresentatives { get; set; }
        public virtual DbSet<MailDestinations> MailDestinations { get; set; }
        public virtual DbSet<ManuscriptSize> ManuscriptSize { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<PressApplicationDeadline> PressApplicationDeadline { get; set; }
        public virtual DbSet<PressApplicationDeadlineDay> PressApplicationDeadlineDay { get; set; }
        public virtual DbSet<ProductionRepresentatives> ProductionRepresentatives { get; set; }
        public virtual DbSet<ProgressRepresentatives> ProgressRepresentatives { get; set; }
        public virtual DbSet<PublisherResponsibleGroups> PublisherResponsibleGroups { get; set; }
        public virtual DbSet<Reads> Reads { get; set; }
        public virtual DbSet<SaleRepresentatives> SaleRepresentatives { get; set; }
        public virtual DbSet<Shutdown> Shutdown { get; set; }
        public virtual DbSet<TeamRepresentatives> TeamRepresentatives { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TransmissionCount> TransmissionCount { get; set; }
        public virtual DbSet<TransmissionForms> TransmissionForms { get; set; }
        public virtual DbSet<UptakeLogs> UptakeLogs { get; set; }
        public virtual DbSet<UserPermissions> UserPermissions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VehicleExclusionConditions> VehicleExclusionConditions { get; set; }
        public virtual DbSet<VehicleExclusionDatas> VehicleExclusionDatas { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehicleSchedules> VehicleSchedules { get; set; }
        public virtual DbSet<IndustryLargeClassifications> IndustryLargeClassifications { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<ProgressSchedules> ProgressSchedules { get; set; }
        public virtual DbSet<ProgressTimetable> ProgressTimetable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AdvertisementValues> AdvertisementValues { get; set; }
        public virtual DbSet<MailContents> MailContents { get; set; }
        public virtual DbSet<ElectronLedger> ElectronLedger { get; set; }
    }
}
