//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizations
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAbbrName { get; set; }
        public string OrganizationCommonName { get; set; }
        public string SuperOrganizationCode { get; set; }
        public string ComapnyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCommonName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> PersonnelManagement { get; set; }
        public Nullable<int> ManagementSectionDivision { get; set; }
        public Nullable<int> Hierarchy { get; set; }
        public string DivisionGroupCommonName { get; set; }
        public string DivisionAbbrName { get; set; }
        public string DivisionCommonName { get; set; }
        public string DepartmentAbbrName { get; set; }
        public string DepartmentCommonName { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    }
}
