//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressSchedules
    {
        public int ID { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public string Updated { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public Nullable<int> MagazineGroupID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> PublicationForm { get; set; }
        public Nullable<int> BusinessRepresentativeID { get; set; }
        public string CompanyName { get; set; }
        public string DivisionGroupName { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Point { get; set; }
        public string ItemName1 { get; set; }
        public string ItemName2 { get; set; }
        public string ItemName3 { get; set; }
        public string ItemName4 { get; set; }
        public string ItemName5 { get; set; }
    }
}
