//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmissionCount
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<System.DateTime> TransmissionDate { get; set; }
        public string TransmissionRepresentativeID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<System.DateTime> CalibrationDate { get; set; }
        public Nullable<int> TransmissionMethod { get; set; }
        public Nullable<int> TransmissionForm { get; set; }
        public string Memo { get; set; }
        public Nullable<int> ElectronLedgerID { get; set; }
        public string TransmissionRepresentativeFree { get; set; }
        public string CompanyName { get; set; }
        public string DivisionGroupName { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string CustomerFree { get; set; }
    }
}
