//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UptakeLogs
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public string UptakeItem { get; set; }
        public string UptakeSuccessNumber { get; set; }
        public string UptakeFailureNumber { get; set; }
        public string UptakeDatas { get; set; }
        public Nullable<System.DateTime> UptaleStart { get; set; }
        public Nullable<System.DateTime> UptaleEnd { get; set; }
    }
}
