//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMP_ZD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> DeleteFlg { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string LastNameKANA { get; set; }
        public string FirstNameKANA { get; set; }
        public string LastNameEN { get; set; }
        public string FirstNameEN { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string DivisionGroupCode { get; set; }
        public string DivisionGroupName { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Add1JNo { get; set; }
        public string Add1CompanyCode { get; set; }
        public string Add1CompanyName { get; set; }
        public string Add1DivisionGroupCode { get; set; }
        public string Add1DivisionGroupName { get; set; }
        public string Add1DivisionCode { get; set; }
        public string Add1DivisionName { get; set; }
        public string Add1DepartmentCode { get; set; }
        public string Add1DepartmentName { get; set; }
        public string Add2JNo { get; set; }
        public string Add2CompanyCode { get; set; }
        public string Add2CompanyName { get; set; }
        public string Add2DivisionGroupCode { get; set; }
        public string Add2DivisionCode { get; set; }
        public string Add2DivisionName { get; set; }
        public string Add2DepartmentCode { get; set; }
        public string Add2DepartmentName { get; set; }
        public string Add3JNo { get; set; }
        public string Add3CompanyCode { get; set; }
        public string Add3CompanyName { get; set; }
        public string Add3DivisionGroupCode { get; set; }
        public string Add3DivisionGroupName { get; set; }
        public string Add3DivisionCode { get; set; }
        public string Add3DivisionName { get; set; }
        public string Add3DepartmentCode { get; set; }
        public string Add3DepartmentName { get; set; }
        public string Add4JNo { get; set; }
        public string Add4CompanyCode { get; set; }
        public string Add4CompanyName { get; set; }
        public string Add4DivisionGroupCode { get; set; }
        public string Add4DivisionGroupName { get; set; }
        public string Add4DivisionCode { get; set; }
        public string Add4DivisionName { get; set; }
        public string Add4DepartmentCode { get; set; }
        public string Add4DepartmentName { get; set; }
        public string Add5JNo { get; set; }
        public string Add5CompanyCode { get; set; }
        public string Add5CompanyName { get; set; }
        public string Add5DivisionGroupCode { get; set; }
        public string Add5DivisionGroupName { get; set; }
        public string Add5DivisionCode { get; set; }
        public string Add5DivisionName { get; set; }
        public string Add5DepartmentCode { get; set; }
        public string Add5DepartmentName { get; set; }
        public string Add6JNo { get; set; }
        public string Add6CompanyCode { get; set; }
        public string Add6CompanyName { get; set; }
        public string Add6DivisionGroupCode { get; set; }
        public string Add6DivisionGroupName { get; set; }
        public string Add6DivisionCode { get; set; }
        public string Add6DivisionName { get; set; }
        public string Add6DepartmentCode { get; set; }
        public string Add6DepartmentName { get; set; }
        public string Add7JNo { get; set; }
        public string Add7CompanyCode { get; set; }
        public string Add7CompanyName { get; set; }
        public string Add7DivisionGroupCode { get; set; }
        public string Add7DivisionGroupName { get; set; }
        public string Add7DivisionCode { get; set; }
        public string Add7DivisionName { get; set; }
        public string Add7DepartmentCode { get; set; }
        public string Add7DepartmentName { get; set; }
        public string Add8JNo { get; set; }
        public string Add8CompanyCode { get; set; }
        public string Add8CompanyName { get; set; }
        public string Add8DivisionGroupCode { get; set; }
        public string Add8DivisionGroupName { get; set; }
        public string Add8DivisionCode { get; set; }
        public string Add8DivisionName { get; set; }
        public string Add8DepartmentCode { get; set; }
        public string Add8DepartmentName { get; set; }
        public string Add9JNo { get; set; }
        public string Add9CompanyCode { get; set; }
        public string Add9CompanyName { get; set; }
        public string Add9DivisionGroupCode { get; set; }
        public string Add9DivisionGroupName { get; set; }
        public string Add9DivisionCode { get; set; }
        public string Add9DivisionName { get; set; }
        public string Add9DepartmentCode { get; set; }
        public string Add9DepartmentName { get; set; }
        public string Add10JNo { get; set; }
        public string Add10CompanyCode { get; set; }
        public string Add10CompanyName { get; set; }
        public string Add10DivisionGroupCode { get; set; }
        public string Add10DivisionGroupName { get; set; }
        public string Add10DivisionCode { get; set; }
        public string Add10DivisionName { get; set; }
        public string Add10DepartmentCode { get; set; }
        public string Add10DepartmentName { get; set; }
        public string Add11JNo { get; set; }
        public string Add11CompanyCode { get; set; }
        public string Add11CompanyName { get; set; }
        public string Add11DivisionGroupCode { get; set; }
        public string Add11DivisionGroupName { get; set; }
        public string Add11DivisionCode { get; set; }
        public string Add11DivisionName { get; set; }
        public string Add11DepartmentCode { get; set; }
        public string Add11DepartmentName { get; set; }
        public string Add12JNo { get; set; }
        public string Add12CompanyCode { get; set; }
        public string Add12CompanyName { get; set; }
        public string Add12DivisionGroupCode { get; set; }
        public string Add12DivisionGroupName { get; set; }
        public string Add12DivisionCode { get; set; }
        public string Add12DivisionName { get; set; }
        public string Add12DepartmentCode { get; set; }
        public string Add12DepartmentName { get; set; }
        public string Add13JNo { get; set; }
        public string Add13CompanyCode { get; set; }
        public string Add13CompanyName { get; set; }
        public string Add13DivisionGroupCode { get; set; }
        public string Add13DivisionGroupName { get; set; }
        public string Add13DivisionCode { get; set; }
        public string Add13DivisionName { get; set; }
        public string Add13DepartmentCode { get; set; }
        public string Add13DepartmentName { get; set; }
        public string Add14JNo { get; set; }
        public string Add14CompanyCode { get; set; }
        public string Add14CompanyName { get; set; }
        public string Add14DivisionGroupCode { get; set; }
        public string Add14DivisionGroupName { get; set; }
        public string Add14DivisionCode { get; set; }
        public string Add14DivisionName { get; set; }
        public string Add14DepartmentCode { get; set; }
        public string Add14DepartmentName { get; set; }
        public string Add15JNo { get; set; }
        public string Add15CompanyCode { get; set; }
        public string Add15CompanyName { get; set; }
        public string Add15DivisionGroupCode { get; set; }
        public string Add15DivisionGroupName { get; set; }
        public string Add15DivisionCode { get; set; }
        public string Add15DivisionName { get; set; }
        public string Add15DepartmentCode { get; set; }
        public string Add15DepartmentName { get; set; }
        public string Email { get; set; }
        public string Add2DivisionGroupName { get; set; }
    }
}
